{{- if and .Values.lidarr.enabled .Values.lidarr.metrics.enabled .Values.lidarr.metrics.serviceMonitor }}
{{- include "k8s-mediamanager.servicemonitor" (dict "context" . "component" "lidarr") }}
{{- end }}
