{{- if .Values.radarr.enabled }}
---
### RADARR — ingress from gateway + prowlarr, egress to qbittorrent + metadata APIs
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "k8s-mediamanager.fullname" . }}-radarr
  labels:
    {{- include "k8s-mediamanager.labels" (dict "context" . "component" "radarr") | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: {{ .Values.radarr.service.port | quote }}
              protocol: TCP
    {{- if .Values.prowlarr.enabled }}
    - fromEndpoints:
        - matchLabels:
            app: prowlarr
      toPorts:
        - ports:
            - port: {{ .Values.radarr.service.port | quote }}
              protocol: TCP
    {{- end }}
    {{- if .Values.radarr.metrics.enabled }}
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: {{ .Values.radarr.metrics.port | quote }}
              protocol: TCP
    {{- end }}
  egress:
    {{- if .Values.qbittorrent.enabled }}
    - toEndpoints:
        - matchLabels:
            app: qbittorrent
      toPorts:
        - ports:
            - port: {{ .Values.qbittorrent.service.webui.port | quote }}
              protocol: TCP
    {{- end }}
    {{- if .Values.prowlarr.enabled }}
    - toEndpoints:
        - matchLabels:
            app: prowlarr
      toPorts:
        - ports:
            - port: {{ .Values.prowlarr.service.port | quote }}
              protocol: TCP
    {{- end }}
    - toFQDNs:
        - matchPattern: "*.themoviedb.org"
        - matchPattern: "api.radarr.video"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
{{- end }}
