{{- if .Values.sonarr.enabled }}
---
### SONARR — ingress from gateway + prowlarr, egress to qbittorrent + metadata APIs
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "k8s-mediamanager.fullname" . }}-sonarr
  labels:
    {{- include "k8s-mediamanager.labels" (dict "context" . "component" "sonarr") | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app: sonarr
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: {{ .Values.sonarr.service.port | quote }}
              protocol: TCP
    {{- if .Values.prowlarr.enabled }}
    - fromEndpoints:
        - matchLabels:
            app: prowlarr
      toPorts:
        - ports:
            - port: {{ .Values.sonarr.service.port | quote }}
              protocol: TCP
    {{- end }}
    {{- if .Values.sonarr.metrics.enabled }}
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: {{ .Values.sonarr.metrics.port | quote }}
              protocol: TCP
    {{- end }}
  egress:
    {{- if .Values.qbittorrent.enabled }}
    - toEndpoints:
        - matchLabels:
            app: qbittorrent
      toPorts:
        - ports:
            - port: {{ .Values.qbittorrent.service.webui.port | quote }}
              protocol: TCP
    {{- end }}
    {{- if .Values.prowlarr.enabled }}
    - toEndpoints:
        - matchLabels:
            app: prowlarr
      toPorts:
        - ports:
            - port: {{ .Values.prowlarr.service.port | quote }}
              protocol: TCP
    {{- end }}
    - toFQDNs:
        - matchPattern: "*.thetvdb.com"
        - matchPattern: "api.sonarr.tv"
        - matchPattern: "*.skyhook.sonarr.tv"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
{{- end }}
