{{- if and .Values.radarr.enabled .Values.radarr.ingress.enabled .Values.gateway.restricted.enabled }}
{{- include "k8s-mediamanager.httproute" (dict
  "context" .
  "component" "radarr"
  "gatewayName" .Values.gateway.restricted.name
  "gatewayNamespace" .Values.gateway.restricted.namespace
  "hostname" .Values.gateway.restricted.hostname
  "path" .Values.radarr.ingress.path
  "port" .Values.radarr.service.port
) }}
{{- end }}
