{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.metrics.enabled .Values.qbittorrent.metrics.serviceMonitor }}
{{- include "k8s-mediamanager.servicemonitor" (dict "context" . "component" "qbittorrent") }}
{{- end }}
