{{- if and .Values.transmission.enabled .Values.transmission.ingress.enabled .Values.gateway.restricted.enabled }}
{{- include "k8s-mediamanager.httproute" (dict
  "context" .
  "component" "transmission"
  "gatewayName" .Values.gateway.restricted.name
  "gatewayNamespace" .Values.gateway.restricted.namespace
  "hostname" .Values.gateway.restricted.hostname
  "path" .Values.transmission.ingress.path
  "port" .Values.transmission.service.rpc.port
) }}
{{- end }}
