{{- if and .Values.transmission.enabled .Values.transmission.metrics.enabled .Values.transmission.metrics.serviceMonitor }}
{{- include "k8s-mediamanager.servicemonitor" (dict "context" . "component" "transmission") }}
{{- end }}
