{{ if .Values.plex.enabled }}
{{- with .Values.plex.volume }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  {{ with .annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ with .labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
  storageClassName: {{ .storageClassName }}
  {{ with .selector }}
  selector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-mediamanager.fullname" . }}-plex
  labels:
    {{- include "k8s-mediamanager.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.plex.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-mediamanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediamanager.selectorLabels" . | nindent 8 }}
        app: plex
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "k8s-mediamanager.serviceAccountName" . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.general.puid }}
        runAsGroup: {{ .Values.general.pgid }}
        fsGroup: {{ .Values.general.pgid }}
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Values.general.sharedStorage.persistentVolumeClaim.claimName }}
        - name: plex-config
          persistentVolumeClaim:
            claimName: {{ .Values.plex.volume.name }}
        - name: plex-transcode
          emptyDir:
            medium: Memory
            sizeLimit: 14Gi
        {{- if .Values.plex.extraVolumes }}
          {{- toYaml .Values.plex.extraVolumes | nindent 8}}
        {{- end }}
      containers:
        - name: plex
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: PUID
              value: "{{ .Values.general.puid }}"
            - name: PGID
              value: "{{ .Values.general.pgid }}"
            - name: PLEX_CLAIM
              value: {{ .Values.plex.claim }}
          image: "{{ .Values.plex.container.image }}:{{ .Values.plex.container.tag }}"
          imagePullPolicy: {{ .Values.plex.container.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.plex.container.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.plex.container.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 10
          ports:
            - name: plex-port
              containerPort: {{ .Values.plex.container.port }}
              protocol: TCP
            - name: dlna-server
              containerPort: 1900
              protocol: UDP
            - name: dlna-http
              containerPort: 32469
              protocol: TCP
            - name: bonjour
              containerPort: 5353
              protocol: UDP
            - name: plex-companion
              containerPort: 8324
              protocol: TCP
            - name: gdm-32410
              containerPort: 32410
              protocol: UDP
            - name: gdm-32412
              containerPort: 32412
              protocol: UDP
            - name: gdm-32413
              containerPort: 32413
              protocol: UDP
            - name: gdm-32414
              containerPort: 32414
              protocol: UDP
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: "{{ .Values.general.sharedStorage.subPaths.movies }}"
            - name: media
              mountPath: /tv
              subPath: "{{ .Values.general.sharedStorage.subPaths.tv }}"
            - name: media
              mountPath: /music
              subPath: "{{ .Values.general.sharedStorage.subPaths.music }}"
            - name: plex-transcode
              mountPath: /transcode
            {{- if .Values.plex.extraVolumeMounts }}
              {{- toYaml .Values.plex.extraVolumeMounts | nindent 12}}
            {{- end }}
          {{- with .Values.plex.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.plex.container.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-mediamanager.fullname" . }}-plex
  labels:
    {{- include "k8s-mediamanager.labels" . | nindent 4 }}
    app: plex
spec:
  ipFamilyPolicy: {{ .Values.general.ipFamilyPolicy }}
  ipFamilies:
    {{ if .Values.general.ipFamilies }}
    {{- toYaml .Values.general.ipFamilies | nindent 4 }}
    {{- end }}
  type: {{ .Values.plex.service.type }}
  ports:
    - port: {{ .Values.plex.service.port }}
      targetPort: {{ .Values.plex.container.port }}
      protocol: TCP
      name: plex-port
      {{ if eq .Values.plex.service.type "NodePort" }}
      nodePort: {{ .Values.plex.service.nodePort }}
      {{ end }}
  selector:
    app: plex
---
### HTTPROUTE
{{ if .Values.plex.ingress.enabled }}
{{- if .Values.general.gateway.public.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "k8s-mediamanager.fullname" . }}-plex
  labels:
    {{- include "k8s-mediamanager.labels" . | nindent 4 }}
    app: plex
spec:
  parentRefs:
    - name: {{ .Values.general.gateway.public.name }}
      namespace: {{ .Values.general.gateway.public.namespace }}
  hostnames:
    - {{ .Values.general.plex_ingress_host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "k8s-mediamanager.fullname" . }}-plex
          port: {{ .Values.plex.service.port }}
{{- end }}
{{ end }}
{{ end }}
